### ISSUE TITLE
Double project is working with Euraka integration 

### ISSUE THREAD

**Issue by mkatkam-nisum-com** [spring-guides/tut-spring-security-and-angular-js#149]
HI ,

I have imported your Double Spring Zuul project and  integrated with Euraka Descovery registry.

After starting up all the servers ,  UI and Resource are registered with Eureka server with Service ids.

But when i call the resource api from the UI projects getting Connection refused exception in both Gateway and UI modules.

Kindly help me out resolve the above problem.

PFA for application.yml files in txt format for Resource, UI and Gateway projects.

[application_gateway.txt](https://github.com/spring-guides/tut-spring-security-and-angular-js/files/1064327/application_gateway.txt)
[application_resource.txt](https://github.com/spring-guides/tut-spring-security-and-angular-js/files/1064325/application_resource.txt)
[application_ui.txt](https://github.com/spring-guides/tut-spring-security-and-angular-js/files/1064326/application_ui.txt)

Below is exception logs .

```
2017-06-09 19:57:00.786  WARN [gateway-server,,,] 1478 --- [tion/x-thrift})] z.r.AsyncReporter$BoundedAsyncReporter   : Dropped 1 spans due to ConnectException(Connection refused (Connection refused))

java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_111]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_111]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_111]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_111]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_111]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_111]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[na:1.8.0_111]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.8.0_111]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.8.0_111]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211) ~[na:1.8.0_111]
	at sun.net.www.http.HttpClient.New(HttpClient.java:308) ~[na:1.8.0_111]
	at sun.net.www.http.HttpClient.New(HttpClient.java:326) ~[na:1.8.0_111]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202) ~[na:1.8.0_111]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138) ~[na:1.8.0_111]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032) ~[na:1.8.0_111]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966) ~[na:1.8.0_111]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316) ~[na:1.8.0_111]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291) ~[na:1.8.0_111]
	at zipkin.reporter.urlconnection.URLConnectionSender.send(URLConnectionSender.java:174) ~[zipkin-sender-urlconnection-0.6.12.jar:na]
	at zipkin.reporter.urlconnection.URLConnectionSender.sendSpans(URLConnectionSender.java:135) ~[zipkin-sender-urlconnection-0.6.12.jar:na]
	at zipkin.reporter.AsyncReporter$BoundedAsyncReporter.flush(AsyncReporter.java:228) [zipkin-reporter-0.6.12.jar:na]
	at zipkin.reporter.AsyncReporter$Builder.lambda$build$0(AsyncReporter.java:153) [zipkin-reporter-0.6.12.jar:na]
	at zipkin.reporter.AsyncReporter$Builder$$Lambda$1.run(Unknown Source) [zipkin-reporter-0.6.12.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
 ```

**Comment by dsyer** [comment]
The exception is nothing to do with the application (UI, gateway etc.). It is a zipkin client telling you it can't find a server to send some trace data. If you want to use zipkin/sleuth, please just read the user guides.
